
import javax.swing.JSpinner;

public class Finish extends javax.swing.JFrame {

    boolean flag=false;
    String type="select";

    public Finish() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bagType_comboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        fast_checkbox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalPrice_tf = new javax.swing.JTextField();
        discountedPrice_tf = new javax.swing.JTextField();
        cancel_btn = new javax.swing.JButton();
        confirm_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gifts_ta = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FINISH");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        bagType_comboBox.setBackground(new java.awt.Color(204, 255, 255));
        bagType_comboBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bagType_comboBox.setForeground(new java.awt.Color(0, 0, 0));
        bagType_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Cloth Bag(₺2)", "Plastic Bag(₺1)" }));
        bagType_comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagType_comboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Select Bag Type");

        fast_checkbox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fast_checkbox.setForeground(new java.awt.Color(0, 51, 51));
        fast_checkbox.setText("I want fast delivery. (₺10)");
        fast_checkbox.setToolTipText("");
        fast_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fast_checkboxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText(" * Deliveries are made within 2 hours. Choose fast delivery to arrive in 30 minutes.");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Total Price:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Discounted Price:");

        totalPrice_tf.setBackground(new java.awt.Color(255, 255, 255));
        totalPrice_tf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalPrice_tf.setForeground(new java.awt.Color(0, 0, 0));
        totalPrice_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPrice_tfActionPerformed(evt);
            }
        });
        totalPrice_tf.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                totalPrice_tfPropertyChange(evt);
            }
        });

        discountedPrice_tf.setBackground(new java.awt.Color(255, 255, 255));
        discountedPrice_tf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        discountedPrice_tf.setForeground(new java.awt.Color(0, 0, 0));
        discountedPrice_tf.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                discountedPrice_tfPropertyChange(evt);
            }
        });

        cancel_btn.setBackground(new java.awt.Color(0, 51, 51));
        cancel_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancel_btn.setForeground(new java.awt.Color(0, 0, 0));
        cancel_btn.setText("CANCEL");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        confirm_btn.setBackground(new java.awt.Color(0, 51, 51));
        confirm_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirm_btn.setForeground(new java.awt.Color(0, 0, 0));
        confirm_btn.setText("CONFIRM AND FINISH");
        confirm_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_btnActionPerformed(evt);
            }
        });
        confirm_btn.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                confirm_btnPropertyChange(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 2));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        gifts_ta.setBackground(new java.awt.Color(204, 255, 255));
        gifts_ta.setColumns(20);
        gifts_ta.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        gifts_ta.setForeground(new java.awt.Color(0, 0, 102));
        gifts_ta.setRows(5);
        gifts_ta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 2));
        gifts_ta.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                gifts_taPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(gifts_ta);

        jLabel5.setBackground(new java.awt.Color(153, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/won_1.gif"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalPrice_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(discountedPrice_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(confirm_btn)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fast_checkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bagType_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(74, 74, 74))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(jLabel5)))))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bagType_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fast_checkbox)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(totalPrice_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(discountedPrice_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirm_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirm_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_btnActionPerformed
        InformationScreen infoScreen = new InformationScreen();
        setVisible(false);
        infoScreen.setVisible(true);
    }//GEN-LAST:event_confirm_btnActionPerformed

    private void totalPrice_tfPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_totalPrice_tfPropertyChange
        totalPrice_tf.setEditable(false);
        totalPrice_tf.setText(Double.toString(Product.totalPrice));
    }//GEN-LAST:event_totalPrice_tfPropertyChange

    private void discountedPrice_tfPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_discountedPrice_tfPropertyChange
        discountedPrice_tf.setEditable(false);

        discountedPrice_tf.setText(String.format("%.2f", Product.discount()));
    }//GEN-LAST:event_discountedPrice_tfPropertyChange

    private void bagType_comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagType_comboBoxActionPerformed

        if(bagType_comboBox.getSelectedItem().equals("Cloth Bag(₺2)")){
            
            if(flag){
                Product.totalPrice -= 1;
            }
            Product.totalPrice += 2;
            flag=true;
            type="cloth";
            
            totalPrice_tf.setText(Double.toString(Product.totalPrice));
            discountedPrice_tf.setText(String.format("%.2f", Product.discount()));
            
        }
        
        if(bagType_comboBox.getSelectedItem().equals("Plastic Bag(₺1)")){
            
            if(flag){
                Product.totalPrice -= 2;
            }
            Product.totalPrice += 1;
            flag=true;
            type="plastic";
            

            totalPrice_tf.setText(Double.toString(Product.totalPrice));
            discountedPrice_tf.setText(String.format("%.2f", Product.discount()));
  
        }

        if(bagType_comboBox.getSelectedItem().equals("Select")){
            confirm_btn.setEnabled(false);
            if(type.equals("cloth")){
                Product.totalPrice -= 2;
            }
            if(type.equals("plastic")){
                Product.totalPrice -= 1;
            }
            
            flag=false;

            totalPrice_tf.setText(Double.toString(Product.totalPrice));
            discountedPrice_tf.setText(String.format("%.2f", Product.discount()));
        }
        if(!bagType_comboBox.getSelectedItem().equals("Select")){
            confirm_btn.setEnabled(true);
        }

    }//GEN-LAST:event_bagType_comboBoxActionPerformed

    private void fast_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fast_checkboxActionPerformed
        
        if(fast_checkbox.isSelected()){
            Product.totalPrice += 10;
        }
        
        totalPrice_tf.setText(Double.toString(Product.totalPrice));
        discountedPrice_tf.setText(String.format("%.2f", Product.discount()));
        
        if(!fast_checkbox.isSelected()){
            Product.totalPrice -= 10;
        }
       
        totalPrice_tf.setText(Double.toString(Product.totalPrice));
        discountedPrice_tf.setText(String.format("%.2f", Product.discount()));
        
    }//GEN-LAST:event_fast_checkboxActionPerformed

    private void confirm_btnPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_confirm_btnPropertyChange
        
    }//GEN-LAST:event_confirm_btnPropertyChange

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        System. exit(0); 
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void totalPrice_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPrice_tfActionPerformed

    }//GEN-LAST:event_totalPrice_tfActionPerformed

    private void gifts_taPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_gifts_taPropertyChange
        gifts_ta.setText("GIFTS YOU WON DUE TO EXCEEDING CERTAIN NUMBER\nOF PRODUCTS IN PURCHASING FROM CATEGORIES:"
                + "\n************************************************\n");
        Clean clean = new Clean();
        PersonalCare perCare = new PersonalCare();
        Other other = new Other();
        Stationary stationary = new Stationary();
        Food food = new Food() {
            @Override
            public String consumptionTime() {
                throw new UnsupportedOperationException("Not supported yet."); 
            }

            @Override
            public String storageCondition() {
                throw new UnsupportedOperationException("Not supported yet.");
            }
        };
        gifts_ta.setEditable(false);
        
        if(ShoppingScreen.cleanCount >=3){
            gifts_ta.append(clean.gift());
        }
        if(ShoppingScreen.careCount >=4){
            gifts_ta.append(perCare.gift());
        }
        if(ShoppingScreen.otherCount >=5){
            gifts_ta.append(other.gift());
        }
        if(ShoppingScreen.stationaryCount >=3){
            gifts_ta.append(stationary.gift());
        }
        if(ShoppingScreen.foodCount >= 7){
            gifts_ta.append(food.gift());
        }
        
    }//GEN-LAST:event_gifts_taPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finish().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bagType_comboBox;
    private javax.swing.JButton cancel_btn;
    public javax.swing.JButton confirm_btn;
    private javax.swing.JTextField discountedPrice_tf;
    public static javax.swing.JCheckBox fast_checkbox;
    private javax.swing.JTextArea gifts_ta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField totalPrice_tf;
    // End of variables declaration//GEN-END:variables
}
